---

- hosts: all
  tasks:
    - name: Print ansible facts type
      debug:
        var: ansible_facts | type_debug

    - name: Print ansible facts
      debug:
        var: ansible_facts

    - name: Set locale var
      set_fact:
        locale = {{ locale }}

    - name: test
      debug:
        var: ansible_facts.env.LANG
      when: ansible_facts.env.LANG != locale
