---
all:
  hosts:
    debian-sharky:
      ansible_host: 192.168.0.2
      ansible_user: root
  vars:
    ansible_python_interpreter: python3

  children:
    personal:
      hosts:
        debian-sharky:

    debian11:
      hosts:
        debian-sharky:

    no_reboot:
      hosts:
        debian-sharky:

    ansible:
      children:
        no_reboot:
